name: simplecloud-api
version: "1.0"
main: app.simplecloud.api.platform.spigot.SpigotApiProvider
api-version: "1.21"

libraries:
  - "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
  - "org.jetbrains.kotlin:kotlin-stdlib:1.8.22"
  - "org.jetbrains.kotlin:kotlin-reflect:1.8.22"